[Tue, 05 Dec 17 19:51:01 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\public\\index.php","line":130,"code":2,"msg":"App\\Frontend\\Controllers\\SomeurlController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('App\\\\Frontend\\\\Co...', 2)\n#1 [internal function]: Phalcon\\Dispatcher->dispatch()\n#2 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#3 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#4 {main}"}

[Tue, 05 Dec 17 19:51:05 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\public\\index.php","line":130,"code":2,"msg":"App\\Frontend\\Controllers\\SomeurlController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('App\\\\Frontend\\\\Co...', 2)\n#1 [internal function]: Phalcon\\Dispatcher->dispatch()\n#2 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#3 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#4 {main}"}

[Tue, 05 Dec 17 19:51:19 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\public\\index.php","line":130,"code":2,"msg":"App\\Frontend\\Controllers\\SomeurlController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('App\\\\Frontend\\\\Co...', 2)\n#1 [internal function]: Phalcon\\Dispatcher->dispatch()\n#2 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#3 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#4 {main}"}

[Tue, 05 Dec 17 20:10:56 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\GoodRepository.php","line":30,"code":"23000","msg":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'sn'","trace":"#0 [internal function]: PDOStatement->execute()\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo->executePrepared(Object(PDOStatement), Array, Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo->execute('INSERT INTO `w_...', Array, Array)\n#3 [internal function]: Phalcon\\Db\\Adapter->insert('w_order', Array, Array, Array)\n#4 [internal function]: Phalcon\\Mvc\\Model->_doLowInsert(Object(Phalcon\\Mvc\\Model\\MetaData\\Memory), Object(Phalcon\\Db\\Adapter\\Pdo\\Mysql), 'w_order', 'id')\n#5 C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\GoodRepository.php(30): Phalcon\\Mvc\\Model->save()\n#6 C:\\Debug\\www\\phalcon\\app\\frontend\\controllers\\GoodController.php(26): App\\Frontend\\Repositories\\GoodRepository->order(Array)\n#7 [internal function]: App\\Frontend\\Controllers\\GoodController->orderAction()\n#8 [internal function]: Phalcon\\Dispatcher->callActionMethod(Object(App\\Frontend\\Controllers\\GoodController), 'orderAction', Array)\n#9 [internal function]: Phalcon\\Dispatcher->dispatch()\n#10 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#11 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#12 {main}"}

[Tue, 05 Dec 17 20:11:05 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\GoodRepository.php","line":30,"code":"23000","msg":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'sn'","trace":"#0 [internal function]: PDOStatement->execute()\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo->executePrepared(Object(PDOStatement), Array, Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo->execute('INSERT INTO `w_...', Array, Array)\n#3 [internal function]: Phalcon\\Db\\Adapter->insert('w_order', Array, Array, Array)\n#4 [internal function]: Phalcon\\Mvc\\Model->_doLowInsert(Object(Phalcon\\Mvc\\Model\\MetaData\\Memory), Object(Phalcon\\Db\\Adapter\\Pdo\\Mysql), 'w_order', 'id')\n#5 C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\GoodRepository.php(30): Phalcon\\Mvc\\Model->save()\n#6 C:\\Debug\\www\\phalcon\\app\\frontend\\controllers\\GoodController.php(26): App\\Frontend\\Repositories\\GoodRepository->order(Array)\n#7 [internal function]: App\\Frontend\\Controllers\\GoodController->orderAction()\n#8 [internal function]: Phalcon\\Dispatcher->callActionMethod(Object(App\\Frontend\\Controllers\\GoodController), 'orderAction', Array)\n#9 [internal function]: Phalcon\\Dispatcher->dispatch()\n#10 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#11 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#12 {main}"}

[Tue, 05 Dec 17 20:11:12 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\GoodRepository.php","line":30,"code":"23000","msg":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'sn'","trace":"#0 [internal function]: PDOStatement->execute()\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo->executePrepared(Object(PDOStatement), Array, Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo->execute('INSERT INTO `w_...', Array, Array)\n#3 [internal function]: Phalcon\\Db\\Adapter->insert('w_order', Array, Array, Array)\n#4 [internal function]: Phalcon\\Mvc\\Model->_doLowInsert(Object(Phalcon\\Mvc\\Model\\MetaData\\Memory), Object(Phalcon\\Db\\Adapter\\Pdo\\Mysql), 'w_order', 'id')\n#5 C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\GoodRepository.php(30): Phalcon\\Mvc\\Model->save()\n#6 C:\\Debug\\www\\phalcon\\app\\frontend\\controllers\\GoodController.php(26): App\\Frontend\\Repositories\\GoodRepository->order(Array)\n#7 [internal function]: App\\Frontend\\Controllers\\GoodController->orderAction()\n#8 [internal function]: Phalcon\\Dispatcher->callActionMethod(Object(App\\Frontend\\Controllers\\GoodController), 'orderAction', Array)\n#9 [internal function]: Phalcon\\Dispatcher->dispatch()\n#10 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#11 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#12 {main}"}

